(package-refresh-contents)
(package-install 'use-package)
(package-install 'auto-highlight-symbol)
(package-install 'auto-complete)
(package-install 'highlight-parentheses)
(package-install 'clipmon)
(package-install 'highlight-indent-guides)
(package-install 'doom-themes)
(package-install 'go-mode)
(package-install 'haskell-mode)
(package-install 'futhark-mode)
(package-install 'tuareg)
(package-install 'julia-mode)
(package-install 'rust-mode)
(package-install 'spacemacs-theme)
(package-install 'markdown-mode)
(package-install 'elixir-mode)
(package-install 'scala-mode)
